language: go

go:
- 1.8.x

before_install:
- make ci_deps

script:
- go test
- go test -race -coverprofile=coverage.txt -covermode=atomic
#- go test -v -coverprofile=coverage.out -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

