language: go

go:
- 1.8.x

before_install:
- make ci_deps

script:
- go test
- go test -race -coverprofile=coverage.txt -covermode=atomic
- go test -v -covermode=count -coverprofile=coverage.out
- goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
- bash <(curl -s https://codecov.io/bash)
